import Link from "next/link";
import { Geist, Geist_Mono, Montserrat } from "next/font/google";
import "./globals.scss";
import "@/components/ripple.js"; // If using Next.js alias (check `jsconfig.json`)

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata = {
  title: "Church Song Directory",
  description: "Generated by Johanan John",
};

export default function RootLayout({ children }) {
  // useEffect(() => {
  //   if (typeof window !== "undefined") {
  //     import("@/components/ripple.js");
  //   }
  // }, []);

  return (
    <html lang="en">
      <head>
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
        {/* <script src="@/components/ripple.js" defer></script> */}
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${montserrat.variable} antialiased`}
      >
        <header className="flex justify-between bg-white items-center py-4 px-8 sticky top-0 z-50">
          <div>

          </div>
          <div>
            <ul className="list-none flex gap-5 text-sky-600 relative text-lg">
              <li className="group">
                <Link href={"/"} className="relative inline-block">
                  <span>Home</span>
                  <span className="absolute bottom-0 left-0 w-0 h-0.5 bg-sky-500 transition-all duration-300 group-hover:w-full"></span>
                </Link>
              </li>
              {/* <li className="group">
                <Link href={"/songs"} className="relative inline-block">
                  <span>Songs</span>
                  <span className="absolute bottom-0 left-0 w-0 h-0.5 bg-sky-500 transition-all duration-300 group-hover:w-full"></span>
                </Link>
              </li> */}
              <li className="group">
                <Link href={"/about"} className="relative inline-block">
                  <span>About</span>
                  <span className="absolute bottom-0 left-0 w-0 h-0.5 bg-sky-500 transition-all duration-300 group-hover:w-full"></span>
                </Link>
              </li>
              <li className="group">
                <Link href={"/contact"} className="relative inline-block">
                  <span>Contact</span>
                  <span className="absolute bottom-0 left-0 w-0 h-0.5 bg-sky-500 transition-all duration-300 group-hover:w-full"></span>
                </Link>
              </li>
              <li className="group">
                <Link href={"/login"} className="relative inline-block">
                  <span
                    className="ripple-container relative overflow-hidden rounded transition-all duration-300 
                    group-hover:bg-sky-500 group-hover:text-white group-hover:px-3 group-hover:py-2">
                    Login
                  </span>
                </Link>
              </li>
            </ul>
          </div>
        </header>
        <div>
          {children}
        </div>
        <footer>

        </footer>
      </body>
    </html>
  );
}
